# Site settings
title: AlgoMOOC materiaali 2015 â€“ MOOC.fi
description: ""
baseurl: "/2015-algoritmit"
url: "http://mooc.fi" 

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

navigation:
  "Viikko 1": "/viikko1.html"
  "Viikko 2": "/viikko2.html"
  "Viikko 3": "/viikko3.html"
  "Viikko 4": "/viikko4.html"
  "Viikko 5": "/viikko5.html"
  "Viikko 6": "/viikko6.html"
